# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.daohang_layout = QtWidgets.QHBoxLayout()
        self.daohang_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.daohang_layout.setContentsMargins(0, 0, 100, 0)
        self.daohang_layout.setSpacing(4)
        self.daohang_layout.setObjectName("daohang_layout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(79, 79, 79);\n"
"color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.daohang_layout.addWidget(self.comboBox)
        self.sousuo_input = QtWidgets.QLineEdit(self.centralwidget)
        self.sousuo_input.setObjectName("sousuo_input")
        self.daohang_layout.addWidget(self.sousuo_input)
        self.sousuo = QtWidgets.QPushButton(self.centralwidget)
        self.sousuo.setText("")
        self.sousuo.setObjectName("sousuo")
        self.daohang_layout.addWidget(self.sousuo)
        self.user_info = QtWidgets.QLabel(self.centralwidget)
        self.user_info.setText("")
        self.user_info.setAlignment(QtCore.Qt.AlignCenter)
        self.user_info.setObjectName("user_info")
        self.daohang_layout.addWidget(self.user_info)
        self.daohang_layout.setStretch(0, 4)
        self.daohang_layout.setStretch(1, 20)
        self.daohang_layout.setStretch(2, 1)
        self.daohang_layout.setStretch(3, 4)
        self.verticalLayout.addLayout(self.daohang_layout)
        self.recommend = QtWidgets.QHBoxLayout()
        self.recommend.setContentsMargins(0, 0, -1, -1)
        self.recommend.setSpacing(0)
        self.recommend.setObjectName("recommend")
        self.left_layout = QtWidgets.QGridLayout()
        self.left_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.left_layout.setContentsMargins(0, 0, 0, 300)
        self.left_layout.setHorizontalSpacing(0)
        self.left_layout.setVerticalSpacing(6)
        self.left_layout.setObjectName("left_layout")
        self.recommend.addLayout(self.left_layout)
        self.right_layout = QtWidgets.QVBoxLayout()
        self.right_layout.setSpacing(0)
        self.right_layout.setObjectName("right_layout")
        self.up_layout = QtWidgets.QHBoxLayout()
        self.up_layout.setSpacing(0)
        self.up_layout.setObjectName("up_layout")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setObjectName("img_label")
        self.up_layout.addWidget(self.img_label)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 411, 89))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.music_form_info = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.music_form_info.setWordWrap(True)
        self.music_form_info.setObjectName("music_form_info")
        self.verticalLayout_2.addWidget(self.music_form_info)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.up_layout.addWidget(self.scrollArea)
        self.up_layout.setStretch(0, 1)
        self.up_layout.setStretch(1, 2)
        self.right_layout.addLayout(self.up_layout)
        self.music_form = QtWidgets.QScrollArea(self.centralwidget)
        self.music_form.setWidgetResizable(True)
        self.music_form.setObjectName("music_form")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 620, 371))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.music_form.setWidget(self.scrollAreaWidgetContents)
        self.right_layout.addWidget(self.music_form)
        self.right_layout.setStretch(0, 1)
        self.right_layout.setStretch(1, 4)
        self.recommend.addLayout(self.right_layout)
        self.recommend.setStretch(0, 1)
        self.recommend.setStretch(1, 4)
        self.verticalLayout.addLayout(self.recommend)
        self.process_layout = QtWidgets.QVBoxLayout()
        self.process_layout.setSpacing(0)
        self.process_layout.setObjectName("process_layout")
        self.verticalLayout.addLayout(self.process_layout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 12)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.sousuo_input)
        MainWindow.setTabOrder(self.sousuo_input, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.music_form)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img_label.setText(_translate("MainWindow", "TextLabel"))
        self.music_form_info.setText(_translate("MainWindow", "TextLabel"))

